### PR TITLE
Recommend switcheroo-control

### PR DESCRIPTION
**Pull request by vasi**
New in 5.109, as documented here: https://mail.kde.org/pipermail/distributions/2023-August/001398.html

### CODE REVIEW

**Comment by vasi** [comment]
@berolinux please take a look

**Comment by fedya** [comment]
looks good, but at first you need to add such package to the repo

**Comment by vasi** [comment]
Oh, I assumed that since it's [already used here](https://github.com/OpenMandrivaAssociation/budgie-desktop/blob/2a40bf4bd98450b89d221dda1b7db6b775a73b87/budgie-desktop.spec#L79), it must be present. But you seem to be correct that it is in fact missing.

**Comment by berolinux** [comment]
Thanks, we should definitely add this (once the package is in)

**Comment by AngryPenguinPL** [comment]
Looks like project was archived. https://gitlab.freedesktop.org/hadess/switcheroo-control/

**Comment by berolinux** [comment]
Package added and MR merged, thanks

**Comment by berolinux** [comment]
Also added to kf6-kio

**Pull request merged**
